export const PERMISSIONS = {
  // Generic CRUD
  READ: 'read',
  WRITE: 'write',
  UPDATE: 'update',
  DELETE: 'delete',
  // Workflow-specific
  APPROVE: 'approve',
  REJECT: 'reject',
  TRANSFER: 'transfer',
  AUDIT: 'audit',
  BOOKING: 'booking',
  // Resource-scoped (dotted, enterprise granular)
  DEPARTMENT_READ: 'department.read',
  DEPARTMENT_CREATE: 'department.create',
  DEPARTMENT_UPDATE: 'department.update',
  DEPARTMENT_DELETE: 'department.delete',
  DEPARTMENT_MANAGE: 'department.manage',
  EMPLOYEE_READ: 'employee.read',
  EMPLOYEE_CREATE: 'employee.create',
  EMPLOYEE_UPDATE: 'employee.update',
  EMPLOYEE_DELETE: 'employee.delete',
  EMPLOYEE_MANAGE: 'employee.manage',
  ASSET_READ: 'asset.read',
  ASSET_CREATE: 'asset.create',
  ASSET_UPDATE: 'asset.update',
  ASSET_DELETE: 'asset.delete',
  ASSET_ALLOCATE: 'asset.allocate',
  ASSET_TRANSFER: 'asset.transfer',
  ASSET_MANAGE: 'asset.manage',
  MAINTENANCE_READ: 'maintenance.read',
  MAINTENANCE_APPROVE: 'maintenance.approve',
  MAINTENANCE_MANAGE: 'maintenance.manage',
  AUDIT_READ: 'audit.read',
  AUDIT_MANAGE: 'audit.manage',
  BOOKING_READ: 'booking.read',
  BOOKING_CREATE: 'booking.create',
  BOOKING_MANAGE: 'booking.manage',
  NOTIFICATION_READ: 'notification.read',
  NOTIFICATION_MANAGE: 'notification.manage',
  ACTIVITY_READ: 'activity.read',
  ACTIVITY_MANAGE: 'activity.manage',
  AUDIT_TRAIL_READ: 'audit_trail.read',
  AUDIT_TRAIL_MANAGE: 'audit_trail.manage',
  REPORT_VIEW: 'report.view',
  REPORT_EXPORT: 'report.export',
  DASHBOARD_VIEW: 'dashboard.view',
  SETTINGS_READ: 'settings.read',
  SETTINGS_MANAGE: 'settings.manage',
  USER_PROMOTE: 'user.promote',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS: Permission[] = Object.values(PERMISSIONS);

export interface PermissionDefinition {
  key: Permission;
  description: string;
  group: string;
}

export const PERMISSION_DEFINITIONS: PermissionDefinition[] = [
  { key: PERMISSIONS.READ, description: 'Read access to resources', group: 'common' },
  { key: PERMISSIONS.WRITE, description: 'Create resources', group: 'common' },
  { key: PERMISSIONS.UPDATE, description: 'Update resources', group: 'common' },
  { key: PERMISSIONS.DELETE, description: 'Delete resources', group: 'common' },
  { key: PERMISSIONS.APPROVE, description: 'Approve workflow requests', group: 'workflow' },
  { key: PERMISSIONS.REJECT, description: 'Reject workflow requests', group: 'workflow' },
  { key: PERMISSIONS.TRANSFER, description: 'Request asset transfers', group: 'workflow' },
  { key: PERMISSIONS.AUDIT, description: 'Perform audits', group: 'workflow' },
  { key: PERMISSIONS.BOOKING, description: 'Create bookings', group: 'workflow' },
  { key: PERMISSIONS.DEPARTMENT_READ, description: 'View departments', group: 'department' },
  { key: PERMISSIONS.DEPARTMENT_CREATE, description: 'Create departments', group: 'department' },
  { key: PERMISSIONS.DEPARTMENT_UPDATE, description: 'Update departments', group: 'department' },
  { key: PERMISSIONS.DEPARTMENT_DELETE, description: 'Delete departments', group: 'department' },
  { key: PERMISSIONS.DEPARTMENT_MANAGE, description: 'Manage departments', group: 'department' },
  { key: PERMISSIONS.EMPLOYEE_READ, description: 'View employees', group: 'employee' },
  { key: PERMISSIONS.EMPLOYEE_CREATE, description: 'Create employees', group: 'employee' },
  { key: PERMISSIONS.EMPLOYEE_UPDATE, description: 'Update employees', group: 'employee' },
  { key: PERMISSIONS.EMPLOYEE_DELETE, description: 'Delete employees', group: 'employee' },
  { key: PERMISSIONS.EMPLOYEE_MANAGE, description: 'Manage employees', group: 'employee' },
  { key: PERMISSIONS.ASSET_READ, description: 'View assets', group: 'asset' },
  { key: PERMISSIONS.ASSET_CREATE, description: 'Register assets', group: 'asset' },
  { key: PERMISSIONS.ASSET_UPDATE, description: 'Update assets', group: 'asset' },
  { key: PERMISSIONS.ASSET_DELETE, description: 'Delete assets', group: 'asset' },
  { key: PERMISSIONS.ASSET_ALLOCATE, description: 'Allocate assets', group: 'asset' },
  { key: PERMISSIONS.ASSET_TRANSFER, description: 'Transfer assets', group: 'asset' },
  { key: PERMISSIONS.ASSET_MANAGE, description: 'Manage assets', group: 'asset' },
  { key: PERMISSIONS.MAINTENANCE_READ, description: 'View maintenance', group: 'maintenance' },
  { key: PERMISSIONS.MAINTENANCE_APPROVE, description: 'Approve maintenance', group: 'maintenance' },
  { key: PERMISSIONS.MAINTENANCE_MANAGE, description: 'Manage maintenance', group: 'maintenance' },
  { key: PERMISSIONS.AUDIT_READ, description: 'View audits', group: 'audit' },
  { key: PERMISSIONS.AUDIT_MANAGE, description: 'Manage audits', group: 'audit' },
  { key: PERMISSIONS.BOOKING_READ, description: 'View bookings', group: 'booking' },
  { key: PERMISSIONS.BOOKING_CREATE, description: 'Create bookings', group: 'booking' },
  { key: PERMISSIONS.BOOKING_MANAGE, description: 'Manage all bookings', group: 'booking' },
  { key: PERMISSIONS.NOTIFICATION_READ, description: 'View notifications', group: 'notification' },
  { key: PERMISSIONS.NOTIFICATION_MANAGE, description: 'Manage notifications', group: 'notification' },
  { key: PERMISSIONS.ACTIVITY_READ, description: 'View activity logs', group: 'activity' },
  { key: PERMISSIONS.ACTIVITY_MANAGE, description: 'Manage activity logs', group: 'activity' },
  { key: PERMISSIONS.AUDIT_TRAIL_READ, description: 'View audit trail', group: 'audit-trail' },
  { key: PERMISSIONS.AUDIT_TRAIL_MANAGE, description: 'Manage audit trail', group: 'audit-trail' },
  { key: PERMISSIONS.REPORT_VIEW, description: 'View reports', group: 'report' },
  { key: PERMISSIONS.REPORT_EXPORT, description: 'Export reports', group: 'report' },
  { key: PERMISSIONS.DASHBOARD_VIEW, description: 'View dashboard', group: 'dashboard' },
  { key: PERMISSIONS.SETTINGS_READ, description: 'View settings', group: 'settings' },
  { key: PERMISSIONS.SETTINGS_MANAGE, description: 'Manage settings', group: 'settings' },
  { key: PERMISSIONS.USER_PROMOTE, description: 'Promote users to other roles', group: 'user' },
];

export const DEFAULT_ROLE_PERMISSIONS: Record<string, Permission[]> = {
  Admin: [...ALL_PERMISSIONS],
  'Asset Manager': [
    PERMISSIONS.READ,
    PERMISSIONS.WRITE,
    PERMISSIONS.UPDATE,
    PERMISSIONS.DELETE,
    PERMISSIONS.APPROVE,
    PERMISSIONS.REJECT,
    PERMISSIONS.TRANSFER,
    PERMISSIONS.AUDIT,
    PERMISSIONS.BOOKING,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.ASSET_READ,
    PERMISSIONS.ASSET_CREATE,
    PERMISSIONS.ASSET_UPDATE,
    PERMISSIONS.ASSET_DELETE,
    PERMISSIONS.ASSET_ALLOCATE,
    PERMISSIONS.ASSET_TRANSFER,
    PERMISSIONS.ASSET_MANAGE,
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.MAINTENANCE_APPROVE,
    PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.AUDIT_MANAGE,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_MANAGE,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_MANAGE,
    PERMISSIONS.ACTIVITY_READ,
    PERMISSIONS.ACTIVITY_MANAGE,
    PERMISSIONS.AUDIT_TRAIL_READ,
    PERMISSIONS.AUDIT_TRAIL_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_MANAGE,
  ],
  'Department Head': [
    PERMISSIONS.READ,
    PERMISSIONS.WRITE,
    PERMISSIONS.UPDATE,
    PERMISSIONS.APPROVE,
    PERMISSIONS.REJECT,
    PERMISSIONS.TRANSFER,
    PERMISSIONS.AUDIT,
    PERMISSIONS.BOOKING,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.ASSET_READ,
    PERMISSIONS.ASSET_ALLOCATE,
    PERMISSIONS.ASSET_TRANSFER,
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_MANAGE,
    PERMISSIONS.ACTIVITY_READ,
    PERMISSIONS.AUDIT_TRAIL_READ,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.DASHBOARD_VIEW,
  ],
  Employee: [
    PERMISSIONS.READ,
    PERMISSIONS.BOOKING,
    PERMISSIONS.TRANSFER,
    PERMISSIONS.ASSET_READ,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.ACTIVITY_READ,
    PERMISSIONS.AUDIT_TRAIL_READ,
    PERMISSIONS.DASHBOARD_VIEW,
  ],
};

export const ROLE_NAMES = ['Admin', 'Asset Manager', 'Department Head', 'Employee'] as const;
export type RoleName = (typeof ROLE_NAMES)[number];
